# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: CmdLine@2
  inputs:
    script: |
      terraform init
      terraform validate
      terraform destroy
      terraform plan
      terraform apply
    workingDirectory: '/home/ec2-user/sampletf/'